site_url: https://invisible-new.netlify.app


publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: assests/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'Globals'
    label: 'globals'
    files: 
    - folder: 'content/global/data.json'
      label : 'Footer'
      name : 'footer'
      fields:
      - { label: 'Title ', name: 'footertitle', widget: 'string',}
      - { label: 'Description', name: 'description', widget: 'string' }
      

    
  
